// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(UniProfileDbContext))]
    [Migration("20221225111435_reg")]
    partial class reg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.DegreeModel", b =>
                {
                    b.Property<int>("Degree_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Degree_ID"));

                    b.Property<string>("Academic_prog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Admission_Requirements_ID")
                        .HasColumnType("int");

                    b.Property<string>("Affiliated_Uni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Career_Opurtunity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course_Fee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degre_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Degree_Content_ID")
                        .HasColumnType("int");

                    b.Property<string>("Degree_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree_Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uni_ID")
                        .HasColumnType("int");

                    b.HasKey("Degree_ID");

                    b.HasIndex("Uni_ID");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("WebApplication1.Models.UniProfileModel", b =>
                {
                    b.Property<int>("Uni_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uni_ID"));

                    b.Property<string>("ImageExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilPic_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uni_Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uni_FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("Uni_FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uni_ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uni_ID");

                    b.ToTable("UniProfiles");
                });

            modelBuilder.Entity("WebApplication1.Models.DegreeModel", b =>
                {
                    b.HasOne("WebApplication1.Models.UniProfileModel", "UniProfiles")
                        .WithMany()
                        .HasForeignKey("Uni_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
